"""
Django settings for USTD_Dev_all project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import django
from django.utils.encoding import force_str

django.utils.encoding.force_text = force_str
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u4zcyh8bb8(mr29wha&gticdkjo=f6*!5d^yr_$e__k*lva&u*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'USTD_App1',
    'notifications',
    'import_export',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 会话存储引擎

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'USTD_Dev_all.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

MEDIA_URL = '/media/'  # 上传图片存储路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

WSGI_APPLICATION = 'USTD_Dev_all.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {  # 数据库配置
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
LANGUAGE_CODE = 'zh-hans'
SIMPLEUI_LOGO = '/static/image/AdminLogo.jpg'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'  # 静态文件配置路径

STATICFILES_DIRS = [
    (os.path.join(BASE_DIR, 'static')),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login/'
SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单。
    'system_keep': False,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。 空列表[] 为全部不显示.
    'menu_display': ['学生信息管理','综测权重系数设置','活动信息管理','材料审核','学业预警管理','notifications', '权限认证'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': False,
    'menus': [
        {
            'app': 'auth',
            'name': '权限认证',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户列表',
                    'icon': 'fa fa-user',
                    'url': 'auth/user/'
                },
                {
                    'name': '用户组',
                    'icon': 'fa fa-th-list',
                    'url': 'auth/group/'
                }
            ]
        },

        {
            'name': '学生信息管理',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '学生信息',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/student/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '课程',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/coursemessage/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '综测总评成绩',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/overallscore/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '课程成绩',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/course/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '知识学习',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/learning/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '创新创业',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/innovation/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '专业技术',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/majortechnology/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '管理实践',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/manage/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '综合发展',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/comprehensivedevelopment/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        {
            'name': '综测权重系数设置',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '综测权重系数',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/weight/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        {
            'name': '活动信息管理',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '活动汇总表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/activity/',
                    'icon': 'fa fa-tasks'
                },
            {
                    'name': '活动报名表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/application/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        {
            'name': '材料审核',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '审核材料表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/shenhe/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        {
            'name': '学业预警管理',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '学业要求',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/graduationrequirement/',
                    'icon': 'fa fa-tasks'
                },
{
                    'name': '学业预警',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/early_warning/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        {
            'name': 'notifications',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': 'notifications',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/USTD_App1/notifications/',
                    'icon': 'fa fa-tasks'
                },

            ]
        },
    ]
}