# Generated by Django 2.1.15 on 2022-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USTD_App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('Employeeno', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='职工号')),
                ('password', models.IntegerField(default=0, null=True, verbose_name='密码')),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='ComprehensiveDevelopment',
            fields=[
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('sno', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='学号')),
                ('physical', models.IntegerField(default=0, null=True, verbose_name='体育评分')),
                ('Volunteer', models.IntegerField(default=0, verbose_name='志愿活动评分')),
                ('Labor', models.IntegerField(default=0, verbose_name='劳务活动评分')),
                ('morality', models.IntegerField(default=0, null=True, verbose_name='思想道德评分')),
            ],
            options={
                'db_table': 'ComprehensiveDevelopment',
            },
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('sno', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='学号')),
                ('ContestRating', models.IntegerField(default=0, verbose_name='竞赛评分')),
                ('PatentRcoring', models.IntegerField(default=0, verbose_name='专利评分')),
                ('EntrepreneurialAchievement', models.IntegerField(default=0, verbose_name='创业成果评分')),
            ],
            options={
                'db_table': 'Innovation',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('sno', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='学号')),
                ('java', models.IntegerField(default=0, null=True, verbose_name='java课程')),
                ('dataStructure', models.IntegerField(default=0, null=True, verbose_name='数据结构')),
                ('Gaverage', models.IntegerField(default=0, null=True, verbose_name='平均绩点')),
            ],
            options={
                'db_table': 'Knowledge',
            },
        ),
        migrations.CreateModel(
            name='majorTechnology',
            fields=[
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('sno', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='学号')),
                ('ProjectPractice', models.IntegerField(default=0, null=True, verbose_name='项目实践')),
                ('PaperGrading', models.IntegerField(default=0, verbose_name='论文评分')),
                ('StudentTutor', models.IntegerField(default=0, null=True, verbose_name='学生导师评分')),
            ],
            options={
                'db_table': 'majorTechnology',
            },
        ),
        migrations.CreateModel(
            name='manage',
            fields=[
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('sno', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='学号')),
                ('community', models.IntegerField(default=0, verbose_name='社团工作评分')),
                ('StudentWork', models.IntegerField(default=0, verbose_name='学生工作评分')),
                ('ProjectTeam', models.IntegerField(default=0, null=True, verbose_name='项目团队评分')),
            ],
            options={
                'db_table': 'manage',
            },
        ),
        migrations.CreateModel(
            name='responsible',
            fields=[
                ('name', models.CharField(max_length=200, null=True, verbose_name='姓名')),
                ('Employeeno', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='职工号')),
                ('password', models.IntegerField(default=0, null=True, verbose_name='密码')),
            ],
            options={
                'db_table': 'responsible',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='pwd',
            field=models.IntegerField(default=123456, verbose_name='密码'),
        ),
        migrations.AlterModelTable(
            name='score',
            table='Score',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
