# Generated by Django 3.2 on 2023-04-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USTD_App1', '0002_activity_course_graduationrequirement_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sp',
            new_name='major',
        ),
        migrations.AddField(
            model_name='student',
            name='banji',
            field=models.CharField(max_length=200, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='院系'),
        ),
    ]
