# Generated by Django 2.1.15 on 2022-12-19 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('USTD_App1', '0002_auto_20221218_2043'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrator',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comprehensivedevelopment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='innovation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='knowledge',
            table=None,
        ),
        migrations.AlterModelTable(
            name='majortechnology',
            table=None,
        ),
        migrations.AlterModelTable(
            name='manage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='responsible',
            table=None,
        ),
        migrations.AlterModelTable(
            name='score',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
