# Generated by Django 4.1.4 on 2022-12-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USTD_App1', '0003_auto_20221219_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='shenhe',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='学号')),
                ('miaoshu', models.CharField(max_length=200, null=True, verbose_name='材料描述')),
                ('leibie', models.CharField(max_length=200, null=True, verbose_name='材料类别')),
                ('image', models.ImageField(default=0, null=True, upload_to='', verbose_name='材料图片')),
            ],
            options={
                'db_table': 'shenhe',
            },
        ),
        migrations.AlterModelTable(
            name='administrator',
            table='administrator',
        ),
        migrations.AlterModelTable(
            name='comprehensivedevelopment',
            table='ComprehensiveDevelopment',
        ),
        migrations.AlterModelTable(
            name='innovation',
            table='Innovation',
        ),
        migrations.AlterModelTable(
            name='knowledge',
            table='Knowledge',
        ),
        migrations.AlterModelTable(
            name='majortechnology',
            table='majorTechnology',
        ),
        migrations.AlterModelTable(
            name='manage',
            table='manage',
        ),
        migrations.AlterModelTable(
            name='responsible',
            table='responsible',
        ),
        migrations.AlterModelTable(
            name='score',
            table='Score',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
