# Generated by Django 3.2 on 2023-04-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('USTD_App1', '0003_auto_20230418_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallScore',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='学号')),
                ('total_score', models.IntegerField(default=0, verbose_name='总评成绩')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='USTD_App1.student')),
            ],
            options={
                'verbose_name': '综测总评成绩',
                'verbose_name_plural': '综测总评成绩',
                'db_table': 'OverallScore',
            },
        ),
        migrations.AddConstraint(
            model_name='overallscore',
            constraint=models.CheckConstraint(check=models.Q(('total_score__gte', 0), ('total_score__lte', 100)),
                                              name='total_score'),
        ),
    ]
