# Generated by Django 3.2 on 2023-04-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USTD_App1', '0004_auto_20230418_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overallscore',
            name='student',
        ),
        migrations.AddField(
            model_name='overallscore',
            name='banji',
            field=models.CharField(max_length=200, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='overallscore',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='overallscore',
            name='major',
            field=models.CharField(max_length=200, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='overallscore',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='姓名'),
        ),
    ]
