# Generated by Django 4.1.4 on 2022-12-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USTD_App1', '0004_shenhe_alter_administrator_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shenhe',
            name='no',
            field=models.IntegerField(default=0, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='shenhe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
