# Generated by Django 3.2 on 2023-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USTD_App1', '0005_auto_20230418_2248'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comprehensivedevelopment',
            name='physical_1',
        ),
        migrations.RemoveConstraint(
            model_name='comprehensivedevelopment',
            name='Volunteer',
        ),
        migrations.RemoveConstraint(
            model_name='comprehensivedevelopment',
            name='Labor',
        ),
        migrations.RemoveConstraint(
            model_name='comprehensivedevelopment',
            name='morality',
        ),
        migrations.RemoveConstraint(
            model_name='innovation',
            name='ContestRating',
        ),
        migrations.RemoveConstraint(
            model_name='innovation',
            name='PatentRcoring',
        ),
        migrations.RemoveConstraint(
            model_name='innovation',
            name='EntrepreneurialAchievement',
        ),
        migrations.RemoveConstraint(
            model_name='majortechnology',
            name='ProjectPractice',
        ),
        migrations.RemoveConstraint(
            model_name='majortechnology',
            name='PaperGrading',
        ),
        migrations.RemoveConstraint(
            model_name='majortechnology',
            name='StudentTutor',
        ),
        migrations.RemoveConstraint(
            model_name='manage',
            name='community',
        ),
        migrations.RemoveConstraint(
            model_name='manage',
            name='StudentWork',
        ),
        migrations.RemoveConstraint(
            model_name='manage',
            name='ProjectTeam',
        ),
        migrations.RemoveConstraint(
            model_name='overallscore',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='comprehensivedevelopment',
            name='Labor',
        ),
        migrations.RemoveField(
            model_name='comprehensivedevelopment',
            name='Volunteer',
        ),
        migrations.RemoveField(
            model_name='comprehensivedevelopment',
            name='morality',
        ),
        migrations.RemoveField(
            model_name='comprehensivedevelopment',
            name='physical',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='ContestRating',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='EntrepreneurialAchievement',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='PatentRcoring',
        ),
        migrations.RemoveField(
            model_name='majortechnology',
            name='PaperGrading',
        ),
        migrations.RemoveField(
            model_name='majortechnology',
            name='ProjectPractice',
        ),
        migrations.RemoveField(
            model_name='majortechnology',
            name='StudentTutor',
        ),
        migrations.RemoveField(
            model_name='manage',
            name='ProjectTeam',
        ),
        migrations.RemoveField(
            model_name='manage',
            name='StudentWork',
        ),
        migrations.RemoveField(
            model_name='manage',
            name='community',
        ),
        migrations.AddField(
            model_name='comprehensivedevelopment',
            name='banji',
            field=models.CharField(max_length=200, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='comprehensivedevelopment',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='comprehensivedevelopment',
            name='major',
            field=models.CharField(max_length=200, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='comprehensivedevelopment',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='成绩'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='banji',
            field=models.CharField(max_length=200, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='major',
            field=models.CharField(max_length=200, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='成绩'),
        ),
        migrations.AddField(
            model_name='majortechnology',
            name='banji',
            field=models.CharField(max_length=200, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='majortechnology',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='majortechnology',
            name='major',
            field=models.CharField(max_length=200, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='majortechnology',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='成绩'),
        ),
        migrations.AddField(
            model_name='manage',
            name='banji',
            field=models.CharField(max_length=200, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='manage',
            name='department',
            field=models.CharField(max_length=200, null=True, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='manage',
            name='major',
            field=models.CharField(max_length=200, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='manage',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='成绩'),
        ),
        migrations.AddConstraint(
            model_name='comprehensivedevelopment',
            constraint=models.CheckConstraint(check=models.Q(('total_score__gte', 0), ('total_score__lte', 100)),
                                              name='dev_total_score'),
        ),
        migrations.AddConstraint(
            model_name='innovation',
            constraint=models.CheckConstraint(check=models.Q(('total_score__gte', 0), ('total_score__lte', 100)),
                                              name='innovation_total_score'),
        ),
        migrations.AddConstraint(
            model_name='majortechnology',
            constraint=models.CheckConstraint(check=models.Q(('total_score__gte', 0), ('total_score__lte', 100)),
                                              name='major_technology_total_score'),
        ),
        migrations.AddConstraint(
            model_name='manage',
            constraint=models.CheckConstraint(check=models.Q(('total_score__gte', 0), ('total_score__lte', 100)),
                                              name='manage_total_score'),
        ),
        migrations.AddConstraint(
            model_name='overallscore',
            constraint=models.CheckConstraint(check=models.Q(('total_score__gte', 0), ('total_score__lte', 100)),
                                              name='overall_score_total_score'),
        ),
    ]
