# Generated by Django 4.1.4 on 2022-12-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USTD_App1', '0005_shenhe_no_alter_shenhe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Early_Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.IntegerField(default=0, null=True, verbose_name='最低学分要求')),
                ('compulsory', models.IntegerField(default=0, null=True, verbose_name='必修课成绩')),
                ('elective', models.IntegerField(default=0, null=True, verbose_name='选修课成绩')),
                ('physical', models.IntegerField(default=0, null=True, verbose_name='体测成绩')),
                ('cet4', models.IntegerField(default=0, null=True, verbose_name='四级成绩')),
                ('mandarin', models.IntegerField(default=0, null=True, verbose_name='普通话成绩')),
            ],
            options={
                'verbose_name': '学业预警',
                'verbose_name_plural': '学业预警',
                'db_table': 'Early_Warning',
            },
        ),
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.AlterModelOptions(
            name='comprehensivedevelopment',
            options={'verbose_name': '综合发展', 'verbose_name_plural': '综合发展'},
        ),
        migrations.AlterModelOptions(
            name='innovation',
            options={'verbose_name': '创新创业', 'verbose_name_plural': '创新创业'},
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'verbose_name': '知识学习', 'verbose_name_plural': '知识学习'},
        ),
        migrations.AlterModelOptions(
            name='majortechnology',
            options={'verbose_name': '专业技术', 'verbose_name_plural': '专业技术'},
        ),
        migrations.AlterModelOptions(
            name='manage',
            options={'verbose_name': '管理实践', 'verbose_name_plural': '管理实践'},
        ),
        migrations.AlterModelOptions(
            name='responsible',
            options={'verbose_name': '负责人', 'verbose_name_plural': '负责人'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': '评分', 'verbose_name_plural': '评分'},
        ),
        migrations.AlterModelOptions(
            name='shenhe',
            options={'verbose_name': '审核', 'verbose_name_plural': '审核'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
    ]
