# Generated by Django 4.1.4 on 2022-12-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('USTD_App1', '0007_alter_early_warning_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='early_warning',
            constraint=models.CheckConstraint(check=models.Q(('minimum__gte', 0), ('minimum__lte', 170)),
                                              name='minimum'),
        ),
        migrations.AddConstraint(
            model_name='early_warning',
            constraint=models.CheckConstraint(check=models.Q(('compulsory__gte', 0), ('compulsory__lte', 100)),
                                              name='compulsory'),
        ),
        migrations.AddConstraint(
            model_name='early_warning',
            constraint=models.CheckConstraint(check=models.Q(('elective__gte', 0), ('elective__lte', 100)),
                                              name='elective'),
        ),
        migrations.AddConstraint(
            model_name='early_warning',
            constraint=models.CheckConstraint(check=models.Q(('physical__gte', 0), ('physical__lte', 100)),
                                              name='physical'),
        ),
        migrations.AddConstraint(
            model_name='early_warning',
            constraint=models.CheckConstraint(check=models.Q(('cet4__gte', 0), ('cet4__lte', 750)), name='cet4'),
        ),
        migrations.AddConstraint(
            model_name='early_warning',
            constraint=models.CheckConstraint(check=models.Q(('mandarin__gte', 0), ('mandarin__lte', 100)),
                                              name='mandarin'),
        ),
    ]
